<?
$phrases = [
  'page_home' => 'Home',
  'page_login' => 'Log-in',
  'page_profile' => 'Profile',
  'page_create_thread' => 'Create thread',
  'form_username' => 'Username',
  'form_email' => 'Email address',
  'form_password' => 'Password',
  'form_confirm_password' => 'Confirm password',
  'form_thread_title' => 'Thread title',
  'form_thread_content' => 'Thread content',
  'button_auth' => 'Log-in',
  'button_register' => 'Register',
  'button_logout' => 'Logout',
  'button_create_thread' => 'Create thread',
  'header_auth' => 'Authorization',
  'header_reg' => 'Registration',
  'header_profile' => 'My Profile',
  'header_create_thread' => 'Create thread',
  'notify_beta' => 'NOTE: This is beta version so you may experience bugs',
  'notify_login' => 'I already have an account',
  'notify_register' => 'I don\'t have an account',
  'notify_nothreads' => 'No threads yet :(',
  'notify_threads' => 'Threads',
  'caption_regdate' => 'Created on',
];
?>
